<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-47P2MTB" failures="1" tests="3" name="Regression Test" time="10.55" errors="0" timestamp="2022-11-13T18:50:16 IST">
  <testcase classname="test.SwagLabsLoginTest" name="loginWithInvalidUsername" time="0.623">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at test.SwagLabsLoginTest.loginWithInvalidUsername(SwagLabsLoginTest.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInvalidUsername -->
  <testcase classname="test.SwagLabsLoginTest" name="loginWithValidCredentials" time="1.399"/>
  <testcase classname="test.SwagLabsLoginTest" name="loginWithInvalidPassword" time="0.0">
    <skipped/>
  </testcase> <!-- loginWithInvalidPassword -->
</testsuite> <!-- Regression Test -->
